config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :contribution_rates
  resources :payroll_items
  resources :paychecks
  resources :hours
  resources :rates
  resources :rate_amounts
  resources :rate_classifications
  resources :employee_classifications
  resources :time_periods
  namespace :admin do
      resources :users

      root to: "users#index"
    end
  resources :employees
  get 'employees/generate_paperwork/:id' => 'employees#generate_paperwork_form', :as => 'generate_paperwork_form'
  post 'employees/generate_paperwork/:id' => 'employees#generate_paperwork', :as => 'generate_paperwork'

  devise_for :users
  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/time_period.rb
=begin
  create_table "time_periods", force: :cascade do |t|
    t.string "name"
    t.date "begins"
    t.date "ends"
    t.text "description"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
=end

class TimePeriod < ApplicationRecord
  def self.for_date(date: Date.today)
    TimePeriod.where('begins <= ?', date).where('ends >= ?', date).first
  end
end

app/controllers/time_periods_controller.rb
class TimePeriodsController < ApplicationController
  before_action :set_time_period, only: %i[ show edit update destroy ]

  # GET /time_periods or /time_periods.json
  def index
    @pagy, @time_periods = pagy(TimePeriod.order(sort_sql), items: 25)
  end

  # GET /time_periods/new
  def new
    @time_period = TimePeriod.new
  end

  # GET /time_periods/1/edit
  def edit
  end

  # POST /time_periods or /time_periods.json
  def create
    @time_period = TimePeriod.new(time_period_params)

    if @time_period.save
      redirect_to time_period_url(@time_period), notice: "Time period was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /time_periods/1 or /time_periods/1.json
  def update
    if @time_period.update(time_period_params)
      redirect_to time_period_url(@time_period), notice: "Time period was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /time_periods/1 or /time_periods/1.json
  def destroy
    @time_period.destroy

    redirect_to time_periods_url, notice: "Time period was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_period
      @time_period = TimePeriod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_period_params
      params.require(:time_period).permit(:name, :begins, :ends, :description)
    end
end

app/helpers/time_periods_helper.rb
module TimePeriodsHelper
end

app/views/time_periods/_form.html.erb
<%= form_with(model: time_period, class: "w-full") do |form| %>

  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :name, 'Name', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :name, maxlength: 32, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% time_period.errors.full_messages_for(:name).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>

  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :begins, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.date_field :begins, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% time_period.errors.full_messages_for(:begins).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>

  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :ends, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.date_field :ends, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% time_period.errors.full_messages_for(:ends).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>


  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :description, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_area :description, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% time_period.errors.full_messages_for(:description).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>

  <div class="md:flex md:items-center">
    <div class="md:w-1/3"></div>
    <div class="md:w-2/3">
      <%= form.button class: "shadow bg-green-500 hover:bg-green-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded", type: 'submit' %>
    </div>
  </div>
<% end %>

app/views/time_periods/_time_period.html.erb
<div id="<%= dom_id time_period %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= time_period.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Begins:</strong>
    <%= time_period.begins %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ends:</strong>
    <%= time_period.ends %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= time_period.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this time period", time_period, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this time period', edit_time_period_path(time_period), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/time_periods/edit.html.erb
<%- title "Edit Time Period - #{@time_period.name}" %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Time Period List', time_periods_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Time Period: <%= @time_period.name %></span>
</div>


<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", time_period: @time_period %>
</div>

app/views/time_periods/index.html.erb
<%- title 'List Time Periods' %>
<div class="container mx-auto block">
	<table class="table-auto w-full">
	  <thead>
	    <tr class='bg-teal-100'>
	      <th class='p-3'><%= sortable_link_for :name, type: :alpha %></th>
	      <th class='p-3'><%= sortable_link_for :begins %></th>
	      <th class='p-3'><%= sortable_link_for :ends %></th>
	      <th class='p-3'><%= sortable_link_for :description %></th>
	      <th class='p-3 w-1/5 text-right'><%= link_to 'New Time Period', new_time_period_path, class: 'bg-teal-600 text-gray-100 p-2 mr-2 hover:bg-teal-700 rounded-xl'%></th>
	    </tr>
	  </thead>
	  <tbody>
			<% @time_periods.each do |time_period| %>
	    <tr class='bg-gray-100 hover:bg-gray-200'>
	      <td class='p-1.5'><%= time_period.name %></td>
	      <td class='p-1.5'><%= time_period.begins %></td>
	      <td class='p-1.5'><%= time_period.ends %></td>
	      <td class='p-1.5'><%= time_period.description %></td>
	      <td class='p-1.5 text-right'>
	      	<%= link_to 'Edit', edit_time_period_path(time_period), class: 'bg-blue-200 p-1 mr-1 hover:bg-blue-300 rounded-md'%>
	      	<%= link_to 'Destroy', time_period_path(time_period), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: 'bg-red-200 p-1 mr-1 hover:bg-red-300 rounded-md'%>
				</td>
	    </tr>
			<% end %>
	  </tbody>
	</table>

<div class="flex mt-3 items-center justify-center space-x-4 w-full">
  <%== pagy_nav(@pagy) %>
</div>
<p class="text-center mt-3 text-gray-500"><%== pagy_info @pagy %></p>

</div>

app/views/time_periods/new.html.erb
<%- title 'New Time Period' %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Time Period List', time_periods_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Create New Time Period</span>
</div>


<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", time_period: @time_period %>
</div>