config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :contribution_rates
  resources :payroll_items
  resources :paychecks
  resources :hours
  resources :rates
  resources :rate_amounts
  resources :rate_classifications
  resources :employee_classifications
  resources :time_periods
  namespace :admin do
      resources :users

      root to: "users#index"
    end
  resources :employees
  get 'employees/generate_paperwork/:id' => 'employees#generate_paperwork_form', :as => 'generate_paperwork_form'
  post 'employees/generate_paperwork/:id' => 'employees#generate_paperwork', :as => 'generate_paperwork'

  devise_for :users
  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/employee.rb
=begin
  create_table "employees", force: :cascade do |t|
    t.string "first_name"
    t.string "last_name"
    t.integer "employee_classification_id"
    t.string "address1"
    t.string "address2"
    t.string "city"
    t.string "state"
    t.string "zip"
    t.string "phone"
    t.date "dob"
    t.string "affiliation_organization"
    t.string "affiliation_card_number"
    t.text "notes"
    t.string "payroll_code"
    t.boolean "payroll_active"
    t.string "keycard_number"
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
=end

class Employee < ApplicationRecord
  ORGANIZATIONS = ['None','Local 1','ACT','IATSE','Other']
  scope :active, -> { where(payroll_active: true) }
  scope :inactive, -> { where(payroll_active: false) }  
  
  belongs_to :employee_classification
  
  def full_name
    if first_name.empty? 
      last_name
    else
      "#{last_name}, #{first_name}"
    end
  end
  
  def full_address
    result = ""
    if !address1.empty? || !city.empty? || !state.empty? || !zip.empty? 
      if address2.empty?
        result = "#{address1}, #{city}, #{state}, #{zip}"
      else
        result = "#{address1}, #{address2}, #{city}, #{state}, #{zip}"
      end
    end
    result
  end
  
  def address
    return address1 if address2.empty?
    return address2 if address1.empty?
    return "#{address1}, #{address2}"
  end
  
  def city_state_zip
    return "#{city}, #{state} #{zip}" if !city.empty? && !state.empty? && !zip.empty?
    ""
  end
  
  def self.ordered_list 
    Employee.all.order(:employee_classification_id).order(:last_name).order(:first_name)
  end
  
end

app/controllers/admin/employees_controller.rb
module Admin
  class EmployeesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy generate_paperwork generate_paperwork_form]

  # GET /employees or /employees.json
  def index
    #@employees = Employee.all
    if filter_status == 'active'
      @pagy, @employees = pagy(Employee.active.where("last_name ILIKE ? OR first_name ILIKE ?", search_name, search_name).order(sort_sql).order(:last_name).order(:first_name), items: 25)
    elsif filter_status == 'inactive'
      @pagy, @employees = pagy(Employee.inactive.where("last_name ILIKE ? OR first_name ILIKE ?", search_name, search_name).order(sort_sql).order(:last_name).order(:first_name), items: 25)
    else
      @pagy, @employees = pagy(Employee.where("last_name ILIKE ? OR first_name ILIKE ?", search_name, search_name).order(sort_sql).order(:last_name).order(:first_name), items: 25)
    end
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employee_url(@employee), notice: "Employee was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    if @employee.update(employee_params)
      redirect_to employee_url(@employee), notice: "Employee was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    redirect_to employees_url, notice: "Employee was successfully destroyed."
  end
  
  def generate_paperwork
    @errors = {}
    @defaults = {
      :rate => '62.06',
      :ot_rate => '93.09',
      :rate_uom => 'hour',
      :department_code => '50001-43-00-440-00-000000',
      :department => 'Performance and Campus Operations',
      :job_title => 'Concert Halls - Extra Stagehand Local One',
      :preparer => 'Jason Marsh',
      :preparer_title => 'Director, Event Production',
      :employer => 'LCPA',
      :employer_address => '70 Lincoln Center Plaza',
      :employer_city => 'New York',
      :employer_state => 'NY',
      :employer_zip => '10023',
      :union => 'Local One',
    }
    
    if request.method.upcase == 'POST'
      
      if not params.fetch(:generate).fetch(:ssn).empty?
        @errors[:ssn] = 'SSN format must be nnn-nn-nnnn' unless params.fetch(:generate).fetch(:ssn) =~ /^\d{3}-\d{2}-\d{4}$/
      end
      
      if @errors.empty?
        
        document = HexaPDF::Document.open Rails.root.join('input.pdf')
        
        canvas = document.pages[0].canvas(type: :overlay)
        canvas.font('Helvetica', size: 18 )
        canvas.fill_color('000f85')
        canvas.text("Prepared For: #{@employee.full_name}", at: [80,792-600])

        # payroll notice sheet
        canvas = document.pages[1].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(params[:generate][:department], at: [74,792-69])
        canvas.text(params[:generate][:date], at: [74,792-95])
        canvas.text(@employee.full_name, at: [77,792-189])
        canvas.text(params[:generate][:ssn], at: [66,792-209])
        canvas.text(@employee.dob.strftime('%Y-%m-%d'), at: [338,792-209]) if @employee.dob
        canvas.text(@employee.full_address, at: [114,792-228])
        canvas.text(@employee.phone, at: [92,792-248])
        canvas.text(params[:generate][:job_title], at: [94,792-296])
        canvas.text(params[:generate][:preparer], at: [102,792-314])
        canvas.text(params[:generate][:department], at: [365,792-314])
        canvas.text(params[:generate][:rate], at: [102,792-337])
        canvas.text(params[:generate][:rate_uom], at: [236,792-337])
        canvas.text(params[:generate][:department_code], at: [245,792-359])
        canvas.text('X', at: [247,792-401])
        canvas.text('X', at: [386,792-340])
        canvas.text('X', at: [160,792-477])
        canvas.text(params[:generate][:union], at: [196,792-475])
        canvas.text('X', at: [245,792-510])
        canvas.text('X', at: [518,792-510])
        canvas.text('See rate sheet for additional rates', at: [210,792-544])
        draw_bounding_box(canvas: canvas, start: 638, stop: 538)
        
        
        # rate notification sheet
        canvas = document.pages[2].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(params[:generate][:date], at: [87,792-188])
        canvas.text(@employee.full_name, at: [139,792-212])
        canvas.text(params[:generate][:department], at: [169,792-236])
        canvas.text(params[:generate][:rate], at: [176,792-304])
        canvas.text(params[:generate][:rate_uom], at: [251,792-304])
#        canvas.text('X', at: [49,792-388])
        canvas.text(params[:generate][:ot_rate], at: [159,792-438])
        canvas.text(params[:generate][:date], at: [376,792-585])
#        canvas.text(params[:generate][:preparer], at: [129,792-615])
#        canvas.text(params[:generate][:preparer_title], at: [390,792-615])
        draw_bounding_box(canvas: canvas, start: 617, stop: 201)
        signature_line(canvas: canvas, x: 155, y: 215 , length: 173)

        # w-4
        canvas = document.pages[4].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.first_name, at: [108,792-117])
        canvas.text(@employee.last_name, at: [280,792-117])
        canvas.text(params[:generate][:ssn], at: [472,792-117])
        canvas.text(@employee.address, at: [108,792-139])
        canvas.text(@employee.city_state_zip, at: [108,792-162])
        canvas.text(params[:generate][:date], at: [461,792-618])
        draw_bounding_box(canvas: canvas, start: 695, stop: 153)
        signature_line(canvas: canvas, x: 108, y: 180 , length: 330)
        
        
        # IT-2104
        canvas = document.pages[5].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.first_name, at: [50,792-117])
        canvas.text(@employee.last_name, at: [256,792-117])
        canvas.text(params[:generate][:ssn], at: [430,792-117])
        canvas.text(@employee.address, at: [50,792-140])
        canvas.text(@employee.city_state_zip, at: [50,792-163])
        canvas.text(params[:generate][:date], at: [460,792-347])
        draw_bounding_box(canvas: canvas, start: 697, stop: 441)
        signature_line(canvas: canvas, x: 49, y: 449 , length: 358)

        # I-9
        canvas = document.pages[6].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.first_name, at: [49,792-193])
        canvas.text(@employee.last_name, at: [256,792-193])
        canvas.text(@employee.address, at: [49,792-218])
        canvas.text(@employee.city, at: [302,792-218])
        canvas.text(@employee.state, at: [452,792-218])
        canvas.text(@employee.zip, at: [498,792-218])
        canvas.text(@employee.dob.strftime('%Y-%m-%d'), at: [49,792-243])
        canvas.text(params[:generate][:ssn], at: [157,792-243])
        canvas.text(@employee.phone, at: [447,792-243])
        canvas.text(params[:generate][:date], at: [370,792-371])
        draw_bounding_box(canvas: canvas, start: 620, stop: 418)
        signature_line(canvas: canvas, x: 123, y: 430 , length: 236)

        # I-9 page 2
        canvas = document.pages[7].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.last_name, at: [50,792-140])
        canvas.text(@employee.first_name, at: [261,792-140])

        # check off
        canvas = document.pages[8].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.full_name, at: [102,792-495])
        canvas.text(@employee.address, at: [88,792-518])
        canvas.text(@employee.city, at: [73,792-540])
        canvas.text(params[:generate][:ssn], at: [330,792-540])
        canvas.text(@employee.state, at: [74,792-562])
        canvas.text(@employee.zip, at: [224,792-562])
        canvas.text(params[:generate][:date], at: [330,792-562])
        draw_bounding_box(canvas: canvas, start: 462, stop: 225)
        signature_line(canvas: canvas, x: 350, y: 283 , length: 208)

        # paid family leave
        canvas = document.pages[9].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.full_name, at: [43,792-249])
        canvas.text(@employee.address, at: [43,792-275])
        canvas.text(@employee.city_state_zip, at: [43,792-298])
        canvas.text(@employee.phone, at: [461,792-298])
        canvas.text(params[:generate][:date], at: [483,792-608])
        draw_bounding_box(canvas: canvas, start: 563, stop: 164)
        signature_line(canvas: canvas, x: 127, y: 189 , length: 284)

        # harassment acknowledgement
        canvas = document.pages[10].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.full_name, at: [96,792-293])
        canvas.text(params[:generate][:date], at: [304,792-257])
        draw_bounding_box(canvas: canvas, start: 555, stop: 483)
        signature_line(canvas: canvas, x: 96, y: 541 , length: 141)

        # employment survey
        canvas = document.pages[11].canvas(type: :overlay)
        canvas.font('Helvetica', size: 12 )
        canvas.fill_color('000f85')
        canvas.text(@employee.first_name, at: [118,792-313])
        canvas.text(@employee.last_name, at: [294,792-313])

app/helpers/employees_helper.rb
module EmployeesHelper
  
  def employee_payroll_active_color_code(employee)
    employee.payroll_active? ? "bg-green-100" : "bg-red-100"
  end
  
  def employee_classification_color_code(employee)
    case employee.employee_classification.name
    when 'Basic'
      'bg-green-100'
    when 'Extra'
      'bg-indigo-100'
    when 'Maintenance'
      'bg-emerald-100'
    when 'Retired'
      'bg-yellow-100'
    else
      'bg-gray-100'
    end
  end
end

app/views/employees/edit.html.erb
<%- title "Edit Employee - #{@employee.full_name}" %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Show Record', @employee, class: "mt-2 rounded-lg py-2 px-2 bg-blue-300 inline-block font-medium" %>
    <%= link_to 'Employee List', employees_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Employee: <%= @employee.full_name %></span>
</div>


<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", employee: @employee %>
</div>

app/views/employees/index.html.erb
<%- title 'List Employees' %>
<div class="container mx-auto block">
	<table class="table-auto w-full">
	  <thead>
	    <tr class='bg-teal-100'>
				<th class='p-3 text-left' colspan="5">
          <%= form_tag(request.path, method: "get", class: "inline", data: {controller: 'employees'}) do |f| %>
						<%= select_tag :status, options_for_select({'Active Employees' => 'active','Inactive Employees' => 'inactive','All Employees' => 'all'}, selected: params.permit(:status)[:status]), class: "text-sm", data: {employees_target: 'status', action: 'employees#filter_status_update'}%>
          <% end %>
          <%= form_tag(request.fullpath, method: "get", class: "inline") do %>
						<%= hidden_field_tag( :status, params[:status] ) %>
            <%= text_field_tag(:search_name, params[:search_name], class: "text-sm", placeholder: "Search...") %>
          <% end %>
				</th>
			</tr>
	    <tr class='bg-teal-100'>
	      <th class='p-3 w-1/5'><%= sortable_link_for :last_name, text: "Last Name", type: :alpha %></th>
	      <th class='p-3 w-1/5'><%= sortable_link_for :first_name, text: "First Name", type: :alpha %></th>
	      <th class='p-3 w-1/5'><%= sortable_link_for :payroll_active, text: "Payroll Status" %></th>
	      <th class='p-3 w-1/5'><%= sortable_link_for :employee_classification_id %></th>
	      <th class='p-3 w-1/5 text-right'><%= link_to 'New Employee', new_employee_path, class: 'bg-teal-600 text-gray-100 p-2 mr-2 hover:bg-teal-700 rounded-xl'%></th>
	    </tr>
	  </thead>
	  <tbody>
			<% @employees.each do |employee| %>
	    <tr class='bg-gray-100 hover:bg-gray-200'>
	      <td class='p-1.5'><%= employee.last_name %></td>
	      <td class='p-1.5'><%= employee.first_name %></td>
	      <td class='p-1.5 text-center'>
					<button class="<%= employee_payroll_active_color_code(employee)%> w-1/2"><%= employee.payroll_active? ? "Active" : "Inactive" %></button>
				</td>
	      <td class='p-1.5 text-center'>
					<button class="<%= employee_classification_color_code(employee) %> w-1/2"><%= employee.employee_classification.name %></button>
				</td>
	      <td class='p-1.5 text-right'>
	      	<%= link_to 'Show', employee_path(employee), class: 'bg-green-200 p-1 mr-1 hover:bg-green-300 rounded-md'%>
	      	<%= link_to 'Edit', edit_employee_path(employee), class: 'bg-blue-200 p-1 mr-1 hover:bg-blue-300 rounded-md'%>
	      	<%= link_to 'Destroy', employee_path(employee), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: 'bg-red-200 p-1 mr-1 hover:bg-red-300 rounded-md'%>
				</td>
	    </tr>
			<% end %>
	  </tbody>
	</table>

<div class="flex mt-3 items-center justify-center space-x-4 w-full">
  <%== pagy_nav(@pagy) %>
</div>
<p class="text-center mt-3 text-gray-500"><%== pagy_info @pagy %></p>

</div>

app/views/employees/show.html.erb
<%- title "Employee Details - #{@employee.full_name}" %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Edit Record', edit_employee_path(@employee), class: "mt-2 rounded-lg py-2 px-2 bg-blue-300 inline-block font-medium" %>
   	<%= link_to 'Destroy', employee_path(@employee), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: 'ml-1 rounded-lg py-2 px-2 bg-red-300 inline-block font-medium'%>
    <%= link_to 'Generate Paperwork', generate_paperwork_path(@employee), class: "ml-1 rounded-lg py-2 px-2 bg-purple-300 inline-block font-medium" %>
    <%= link_to 'Employee List', employees_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-300 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Employee: <%= @employee.full_name %></span>
</div>

<div class="flex mx-auto w-full">
	<div class="mx-auto w-full">
		<!-- container with detailed employee record -->
		<div class="mx-auto w-full">
		  <div class="md:flex md:items-center mt-3 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Record Number</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.id %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-3 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Last Name</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.last_name %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">First Name</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.first_name %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Date Of Birth</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.dob %></span>
		    </div>
		  </div>

		  <div class="md:flex md:items-center mt-3 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Address Line 1</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.address1 %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Address Line 2</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.address2 %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">City</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.city %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">State</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.state %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Zip Code</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.zip %></span>
		    </div>
		  </div>

		  <div class="md:flex md:items-center mt-3 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Phone</span>
		    </div>
		    <div class="md:w-2/3">
					<% if @employee.phone.empty? %>
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"></span>
					<% else %>
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= link_to @employee.phone, "tel:#{@employee.phone}" %> (<%= link_to 'SMS', "sms:#{@employee.phone}" %>)</span>
					<% end %>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">E-Mail Address</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= link_to_if (not @employee.email.blank?), @employee.email, "mailto:#{@employee.email}" %></span>
		    </div>
		  </div>

		  <div class="md:flex md:items-center mt-3 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Affiliation Organization</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.affiliation_organization %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Affiliation Card Number</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.affiliation_card_number %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-3 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Payroll Code</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.payroll_code %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Payroll Active</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.payroll_active %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Keycard Number</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.keycard_number %></span>
		    </div>
		  </div>
		  <div class="md:flex md:items-center mt-0 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Classification</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.employee_classification.name %></span>
		    </div>
		  </div>

		  <div class="md:flex md:items-center mt-3 ">
		    <div class="md:w-1/3 ">
					<span class="block text-gray-900 font-bold md:text-right mb-1 md:mb-0 pr-4">Notes</span>
		    </div>
		    <div class="md:w-2/3">
					<span class="block text-gray-700 md:text-left mb-1 md:mb-0 pr-4"><%= @employee.notes %></span>
		    </div>
		  </div>

		</div>
	</div>
	<div class="mx-auto w-full">
		Here goes calculated stats for the employee
	</div>
</div>