config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :contribution_rates
  resources :payroll_items
  resources :paychecks
  resources :hours
  resources :rates
  resources :rate_amounts
  resources :rate_classifications
  resources :employee_classifications
  resources :time_periods
  namespace :admin do
      resources :users

      root to: "users#index"
    end
  resources :employees
  get 'employees/generate_paperwork/:id' => 'employees#generate_paperwork_form', :as => 'generate_paperwork_form'
  post 'employees/generate_paperwork/:id' => 'employees#generate_paperwork', :as => 'generate_paperwork'

  devise_for :users
  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/payroll_item.rb
=begin
  create_table "payroll_items", force: :cascade do |t|
    t.integer "source_hour_id"
    t.integer "payroll_id"
    t.integer "employee_id"
    t.integer "source_rate_id"
    t.integer "source_rate_amount_id"
    t.decimal "amount"
    t.decimal "quantity"
    t.boolean "correction"
    t.text "notes"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.decimal "total"
    t.string "name"
    t.string "short_code"
    t.date "date"
  end
=end

class PayrollItem < ApplicationRecord
  belongs_to :payroll
  belongs_to :source_hour, class_name: 'Hour'
  belongs_to :source_rate, class_name: 'Rate'
  belongs_to :source_rate_amount, class_name: 'RateAmount'
  belongs_to :employee
  
end

app/controllers/payroll_items_controller.rb
class PayrollItemsController < ApplicationController
  before_action :set_payroll_item, only: %i[ show edit update destroy ]

  # GET /payroll_items or /payroll_items.json
  def index
    if filter_payroll_id.empty?
      @pagy, @payroll_items = pagy(PayrollItem.all.order(sort_sql), items: 25)
    else
      @pagy, @payroll_items = pagy(PayrollItem.where(payroll_id: filter_payroll_id).order(sort_sql), items: 25)
    end
  end

  # GET /payroll_items/1 or /payroll_items/1.json
  def show
  end

  # GET /payroll_items/new
  def new
    @payroll_item = PayrollItem.new
  end

  # GET /payroll_items/1/edit
  def edit
  end

  # POST /payroll_items or /payroll_items.json
  def create
    @payroll_item = PayrollItem.new(payroll_item_params)

    respond_to do |format|
      if @payroll_item.save
        format.html { redirect_to payroll_item_url(@payroll_item), notice: "Payroll item was successfully created." }
        format.json { render :show, status: :created, location: @payroll_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payroll_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payroll_items/1 or /payroll_items/1.json
  def update
    respond_to do |format|
      if @payroll_item.update(payroll_item_params)
        format.html { redirect_to payroll_item_url(@payroll_item), notice: "Payroll item was successfully updated." }
        format.json { render :show, status: :ok, location: @payroll_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payroll_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payroll_items/1 or /payroll_items/1.json
  def destroy
    @payroll_item.destroy

    respond_to do |format|
      format.html { redirect_to payroll_items_url, notice: "Payroll item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payroll_item
      @payroll_item = PayrollItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payroll_item_params
      params.require(:payroll_item).permit(:source_hour_id, :payroll_id, :employee_id, :source_rate_id, :source_rate_amount_id, :amount, :quantity, :correction, :notes)
    end
    
    def filter_payroll_id
      params.permit(:payroll_id).fetch(:payroll_id,'')
    end
    
end

app/helpers/payroll_items_helper.rb
module PayrollItemsHelper
  
  def payroll_list_helper
    output = Payroll.ordered_list.map{ |x| [x.full_name, x.id]}
    output.unshift ['All Payrolls', '']
    output
  end

end

app/views/payroll_items/_form.html.erb
<%= form_with(model: payroll_item, class: "w-full max-w-lg") do |form| %>

  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :payroll_id, 'Payroll', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
			<%= form.select :payroll_id, Payroll.ordered_list.map{ |x| [x.full_name, x.id]}, {prompt: true}, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:payroll_id).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :source_hour_id, 'Source Hour', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
			<%= link_to "Hour #{payroll_item.source_hour_id}", hour_path(payroll_item.source_hour)%>( <%= payroll_item.source_hour.date %> )
      <%= form.hidden_field :source_hour_id, maxlength: 255, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:source_hour_id).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :date, 'Date', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.date_field :date, maxlength: 32, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:date).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :employee_id, 'Employee', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
			<%= form.select :employee_id, Employee.ordered_list.map{ |x| [x.full_name, x.id]}, {prompt: true}, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:employee_id).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :source_rate_id, 'Source Rate', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
			<%= link_to payroll_item.source_rate.name, rate_path(payroll_item.source_rate) %>
      <%= form.hidden_field :source_rate_id, maxlength: 255, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:source_rate_id).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :name, 'Rate Name', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :name, maxlength: 255, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:name).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :short_code, 'Short Code', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :short_code, maxlength: 255, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:short_code).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :source_rate_amount_id, 'Source Rate Amount', class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
			<%= link_to number_to_currency(payroll_item.source_rate_amount.amount), rate_amount_path(payroll_item.source_rate_amount) %>
      <%= form.hidden_field :source_rate_amount_id, maxlength: 255, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:source_rate_amount_id).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :amount, 'Amount', maxlength: 64, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :amount, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:amount).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :quantity, 'Quantity', maxlength: 2, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_field :quantity, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:quantity).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :amount, 'Amount', maxlength: 2, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
			Caluted (was: <%= number_to_currency payroll_item.amount %>)
			<% payroll_item.errors.full_messages_for(:amount).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>
  <div class="md:flex md:items-center mt-0 mb-1">
    <div class="md:w-1/3">
      <%= form.label :correction, 'Correction', maxlength: 10, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
			<%= form.check_box :correction, class: 'bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500' %>
			<% payroll_item.errors.full_messages_for(:correction).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>


  <div class="md:flex md:items-center mt-6 mb-1">
    <div class="md:w-1/3">
      <%= form.label :notes, class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="md:w-2/3">
      <%= form.text_area :notes, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500" %>
			<% payroll_item.errors.full_messages_for(:notes).each do |error_message| %>
			  <p class="text-red-500 text-xs italic"><%= error_message %></p>
			<% end %>
    </div>
  </div>

  <div class="md:flex md:items-center">
    <div class="md:w-1/3"></div>
    <div class="md:w-2/3">
      <%= form.button class: "shadow bg-green-500 hover:bg-green-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded", type: 'submit' %>
    </div>
  </div>
<% end %>

app/views/payroll_items/_payroll_item.html.erb
<div id="<%= dom_id payroll_item %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Source hour:</strong>
    <%= payroll_item.source_hour_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Payroll:</strong>
    <%= link_to payroll_item.payroll.full_name, payroll_path(payroll_item.payroll) %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Employee:</strong>
    <%= link_to payroll_item.employee.full_name, employee_path(payroll_item.employee) %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Source rate:</strong>
    <%= payroll_item.source_rate_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Source rate amount:</strong>
    <%= payroll_item.source_rate_amount_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= payroll_item.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Date:</strong>
    <%= payroll_item.date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Short Code:</strong>
    <%= payroll_item.short_code %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= number_to_currency payroll_item.amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= payroll_item.quantity %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= number_to_currency payroll_item.total %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Correction:</strong>
    <%= payroll_item.correction %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= payroll_item.notes %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this payroll item", payroll_item, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this payroll item', edit_payroll_item_path(payroll_item), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/payroll_items/edit.html.erb
<%- title "Edit Payroll Item - #{@payroll_item.id}" %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Payroll Item List', payroll_items_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Payroll Item: <%= @payroll_item.id %></span>
</div>


<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", payroll_item: @payroll_item %>
</div>

app/views/payroll_items/index.html.erb
<%- title 'List Payroll Items' %>
<div class="container mx-auto block">
	<table class="table-auto w-full">
	  <thead>
	    <tr class='bg-teal-100'>
				<th class='p-3 text-left' colspan="5">
          <%= form_tag(request.path, method: "get", class: "inline", data: {controller: 'employees'}) do |f| %>
						Payroll: <%= select_tag :payroll_id, options_for_select(payroll_list_helper, selected: params[:payroll_id]), class: "text-sm", data: {employees_target: 'status', action: 'employees#filter_status_update'}%>
          <% end %>



				</th>
			</tr>
	    <tr class='bg-teal-100'>
	      <th class='p-3'><%= sortable_link_for :employee_id, text: "Employee" %></th>
	      <th class='p-3'><%= sortable_link_for :date %></th>
	      <th class='p-3'><%= sortable_link_for :name %> / <%= sortable_link_for :short_code, text: 'Code' %></th>
	      <th class='p-3'><%= sortable_link_for :quantity %></th>
	      <th class='p-3 w-1/5 text-right'><%= link_to 'New Payroll Item', new_payroll_item_path, class: 'bg-teal-600 text-gray-100 p-2 mr-2 hover:bg-teal-700 rounded-xl'%></th>
	    </tr>
	  </thead>
	  <tbody>
			<% @payroll_items.each do |payroll_item| %>
	    <tr class='bg-gray-100 hover:bg-gray-200'>
	      <td class='p-1.5'><%= payroll_item.employee.full_name %></td>
	      <td class='p-1.5'><%= payroll_item.date %></td>
	      <td class='p-1.5'><%= payroll_item.name %> / <%= payroll_item.short_code %></td>
	      <td class='p-1.5'><%= payroll_item.quantity %></td>
	      <td class='p-1.5 text-right'>
	      	<%= link_to 'Show', payroll_item_path(payroll_item), class: 'bg-green-200 p-1 mr-1 hover:bg-green-300 rounded-md'%>
	      	<%= link_to 'Edit', edit_payroll_item_path(payroll_item), class: 'bg-blue-200 p-1 mr-1 hover:bg-blue-300 rounded-md'%>
	      	<%= link_to 'Destroy', payroll_item_path(payroll_item), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: 'bg-red-200 p-1 mr-1 hover:bg-red-300 rounded-md'%>
				</td>
	    </tr>
			<% end %>
	  </tbody>
	</table>

<div class="flex mt-3 items-center justify-center space-x-4 w-full">
  <%== pagy_nav(@pagy) %>
</div>
<p class="text-center mt-3 text-gray-500"><%== pagy_info @pagy %></p>

</div>

app/views/payroll_items/new.html.erb
<%- title 'New Payroll Item' %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Payroll Item List', payroll_items_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Create New Payroll Item</span>
</div>


<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", payroll_item: @payroll_item %>
</div>

app/views/payroll_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @payroll_item %>

    <%= link_to 'Edit this payroll_item', edit_payroll_item_path(@payroll_item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this payroll_item', payroll_item_path(@payroll_item), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to payroll_items', payroll_items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>