config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :contribution_rates
  resources :payroll_items
  resources :paychecks
  resources :hours
  resources :rates
  resources :rate_amounts
  resources :rate_classifications
  resources :employee_classifications
  resources :time_periods
  namespace :admin do
      resources :users

      root to: "users#index"
    end
  resources :employees
  get 'employees/generate_paperwork/:id' => 'employees#generate_paperwork_form', :as => 'generate_paperwork_form'
  post 'employees/generate_paperwork/:id' => 'employees#generate_paperwork', :as => 'generate_paperwork'

  devise_for :users
  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/rate_amount.rb
=begin
  create_table "rate_amounts", force: :cascade do |t|
    t.integer "rate_id"
    t.integer "time_period_id"
    t.decimal "amount"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
=end

class RateAmount < ApplicationRecord
  belongs_to :time_period
  belongs_to :rate
end

app/controllers/rate_amounts_controller.rb
class RateAmountsController < ApplicationController
  before_action :set_rate_amount, only: %i[ show edit update destroy ]

  # GET /rate_amounts or /rate_amounts.json
  def index
    @pagy, @rate_amounts = pagy(RateAmount.order(sort_sql), items: 25)
  end

  # GET /rate_amounts/new
  def new
    @rate_amount = RateAmount.new
  end

  # GET /rate_amounts/1/edit
  def edit
  end

  # POST /rate_amounts or /rate_amounts.json
  def create
    @rate_amount = RateAmount.new(rate_amount_params)

    if @rate_amount.save
      redirect_to rate_amount_url(@rate_amount), notice: "Rate amount was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rate_amounts/1 or /rate_amounts/1.json
  def update
    if @rate_amount.update(rate_amount_params)
      redirect_to rate_amount_url(@rate_amount), notice: "Rate amount was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /rate_amounts/1 or /rate_amounts/1.json
  def destroy
    @rate_amount.destroy

    redirect_to rate_amounts_url, notice: "Rate amount was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate_amount
      @rate_amount = RateAmount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rate_amount_params
      params.require(:rate_amount).permit(:rate_id, :time_period_id, :amount)
    end
end

app/helpers/rate_amounts_helper.rb
module RateAmountsHelper
end

app/views/rate_amounts/_form.html.erb
<%= form_with(model: rate_amount, class: "contents") do |form| %>
  <% if rate_amount.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(rate_amount.errors.count, "error") %> prohibited this rate_amount from being saved:</h2>

      <ul>
        <% rate_amount.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :rate_id %>
    <%= form.number_field :rate_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :time_period_id %>
    <%= form.number_field :time_period_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/rate_amounts/edit.html.erb
<%- title "Edit Rate Amount - #{@rate_amount.name}" %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Rate Amount List', rate_amounts_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Rate Amount: <%= @rate_amount.name %></span>
</div>


<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", rate_amount: @rate_amount %>
</div>

app/views/rate_amounts/index.html.erb
<%- title 'List Rate Amounts' %>
<div class="container mx-auto block">
	<table class="table-auto w-full">
	  <thead>
	    <tr class='bg-teal-100'>
	      <th class='p-3'><%= sortable_link_for :time_period_id, type: :alpha %></th>
	      <th class='p-3'><%= sortable_link_for :rate_id, type: :alpha %></th>
	      <th class='p-3'><%= sortable_link_for :amount, type: :numeric %></th>
	      <th class='p-3 w-1/5 text-right'><%= link_to 'New Rate Amount', new_rate_amount_path, class: 'bg-teal-600 text-gray-100 p-2 mr-2 hover:bg-teal-700 rounded-xl'%></th>
	    </tr>
	  </thead>
	  <tbody>
			<% @rate_amounts.each do |rate_amount| %>
	    <tr class='bg-gray-100 hover:bg-gray-200'>
	      <td class='p-1.5'><%= rate_amount.time_period.name %></td>
	      <td class='p-1.5'><%= rate_amount.rate.name %></td>
	      <td class='p-1.5'><%= number_to_currency rate_amount.amount %></td>
	      <td class='p-1.5 text-right'>
	      	<%= link_to 'Edit', edit_rate_amount_path(rate_amount), class: 'bg-blue-200 p-1 mr-1 hover:bg-blue-300 rounded-md'%>
	      	<%= link_to 'Destroy', rate_amount_path(rate_amount), data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: 'bg-red-200 p-1 mr-1 hover:bg-red-300 rounded-md'%>
				</td>
	    </tr>
			<% end %>
	  </tbody>
	</table>

<div class="flex mt-3 items-center justify-center space-x-4 w-full">
  <%== pagy_nav(@pagy) %>
</div>
<p class="text-center mt-3 text-gray-500"><%== pagy_info @pagy %></p>

</div>

app/views/rate_amounts/new.html.erb
<%- title 'New Rate Amount' %>
<div class="mx-auto w-full pb-6 text-right">
    <%= link_to 'Rate Amount List', rate_amounts_path, class: "ml-2 rounded-lg py-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>

<div class="mx-auto w-full pb-6">
	<span class="text-4xl font-semibold">Create Rate Amount</span>
</div>


<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", rate_amount: @rate_amount %>
</div>

app/views/rate_amounts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @rate_amount %>

    <%= link_to 'Edit this rate_amount', edit_rate_amount_path(@rate_amount), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this rate_amount', rate_amount_path(@rate_amount), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to rate_amounts', rate_amounts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>